### DISCUSSION TITLE
Is there a way to disable tabs?

### DISCUSSION THREAD

**Discussion by ronildo** [caplin/FlexLayout#354] [Q&A]
I want to make my layout without tabs, anything else would be pretty much the same.

React Mosaic, is very similar to what I need (but that library doesn't have all the features that FlexLayout has).
The widget title bar is the draggable element.
https://nomcopter.github.io/react-mosaic/

Is there any to achieve this?

**Comment by fullergalway** [comment]
I have the same requirement really.

My current approach is to set the tabset with one tab having tabStripHeight=1, and enableDrop=false.

If some way to set the tabStripHeight to zero my problem would be solved!

**Reply by ronildo** [reply]
I actually end up with a solution similar to yours: `enableDrop=false` then I changed the CSS in a way that it looks like one tab only (still under prototype phase, but it will be some how close to the screenshot)

![Screenshot from 2023-01-30 11-32-03](https://user-images.githubusercontent.com/622159/215537184-73faaec8-3a56-487b-ab31-fca98730b3da.png)

**Reply by fullergalway** [reply]
Nice. Looks like you're creating a kewl dashboarding system.

Care to share the css?

**Reply by fullergalway** [reply]
Just found this works to hide the bar on a tabset:
        enableTabStrip: false,

Just need something like that for my border component now.

**Reply by ronildo** [reply]
> Nice. Looks like you're creating a kewl dashboarding system.
> 
> Care to share the css?

I used sass... but shouldn't be hard to change it to css.
I also use this global configs:

```json
"global": {
      "tabEnableClose": false,
      "tabSetEnableDrop": false,
      "tabSetEnableMaximize": false
},
```

```css
body {
  .flexlayout {

    &__splitter {
      background-color: transparent;
    }

    &__tab {
      border-radius: 0 0 8px 8px;
      border: 1px solid #959BA6;
      border-top: 1px solid rgba(#333, .5);
      background-color: #F6F7F9;

      &_button {
        cursor: move;
        justify-content: start;
        width: 100%;

        &_content {
          color: #333;
          font-size: 14px;
        }

        &--selected {
          background-color: #FFF;
        }
      }
    }


    &__tabset {
      border: 1px solid #959BA6;
      border-radius: 8px;

      &-selected {
        background-color: white;
      }

      &_tabbar {

        &_inner_tab_container {
          width: 100%;
        }

      }

    }

  }
}
```
